# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('is_closed', models.BooleanField()),
                ('numeroSolucoes', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemConhecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto_id', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('permalink', models.CharField(max_length=200)),
                ('projeto_knowleds', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ProjetoKnowLeds')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('dataInicio', models.DateTimeField(blank=True, null=True)),
                ('dataFim', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.CharField(max_length=200)),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taiga.Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('is_closed', models.BooleanField()),
                ('numeroSolucoes', models.IntegerField(null=True)),
                ('user', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200, null=True)),
                ('tags', models.CharField(max_length=200)),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taiga.Sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('itemconhecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taiga.ItemConhecimento')),
                ('url', models.CharField(max_length=200)),
            ],
            bases=('taiga.itemconhecimento',),
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('itemconhecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taiga.ItemConhecimento')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('editora', models.CharField(max_length=200)),
                ('edicao', models.CharField(max_length=200)),
            ],
            bases=('taiga.itemconhecimento',),
        ),
        migrations.CreateModel(
            name='PessoaConhecimento',
            fields=[
                ('itemconhecimento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taiga.ItemConhecimento')),
                ('pessoa', models.CharField(max_length=200)),
            ],
            bases=('taiga.itemconhecimento',),
        ),
        migrations.AddField(
            model_name='task',
            name='userStory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taiga.UserStory'),
        ),
        migrations.AddField(
            model_name='issue',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taiga.Projeto'),
        ),
    ]
