# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-15 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetoknowleds',
            name='usuarios',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
