# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiga', '0002_auto_20161015_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetoknowleds',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
